### ISSUE TITLE
self.attention_store = AttentionStore() TypeError: __init__() missing 1 required positional argument: 'attn_res'

### ISSUE THREAD

**Issue by ZhangYang-UCAS** [RoyiRa/Syntax-Guided-Generation#1]
How to solve this issue?
```
Syntax-Guided-Generation/syngen_diffusion_pipeline.py", line 241, in __call__
self.attention_store = AttentionStore()
TypeError: __init__() missing 1 required positional argument: 'attn_res'
```

**Comment by RoyiRa** [comment]
Please provide more details on how to recreate it, what kind of environment are you running, did you change anything, etc...
I don't have any issue running the code. Can you try running the [notebook](https://colab.research.google.com/drive/1Jg6Z41bnVIEmXHcqTP_a8k-2mQcoSGux?usp=sharing) (it should work for you too)?

**Comment by ZhangYang-UCAS** [comment]
> 

I didn't run it successfully because I was using the latest version of diffusers. Now I'm running successfully, I downgraded my diffusers.
Now I found that this work has some problems, it can't deal with space, quantity and size relationship well. Such as "A banana on the left of an apple", or "A cat and a chair, the cat is bigger than chair" , or "Four cars on the street.", can you use other methods to solve these problems in your work?

**Comment by RoyiRa** [comment]
This is correct, SynGen is not designed to address these problems. However, we believe that with some modifications, it can be solved, and are strongly considering it as a next step. I'd be happy to discuss this further by email, if you work on something similar, or have some feedback! You can find my email in the paper.

By the way, you can also run our demo, if you just want to try out some prompts:
https://huggingface.co/spaces/Royir/SynGen
