### ISSUE TITLE
Is it possible to apply SynGen to SDXL?

### ISSUE THREAD

**Issue by jiashenggu** [RoyiRa/Syntax-Guided-Generation#5]
I tried to apply SynGen to SDXL. but it didn't work well. I think this might be due to the scaling of the model size if my implementation is ok? Any ideas on how to do this? I changed the step_size and loss.
[syngen_xl_notebook.zip](https://github.com/RoyiRa/Linguistic-Binding-in-Diffusion-Models/files/14948196/syngen_xl_notebook.zip)

**Comment by RoyiRa** [comment]
I viewed the code, but did not see what exactly has changed in the loss. If you'd like to discuss, please send an email my way and I'd be happy to help.

**Comment by lioo717** [comment]
> I tried to apply SynGen to SDXL. but it didn't work well. I think this might be due to the scaling of the model size if my implementation is ok? Any ideas on how to do this? I changed the step_size and loss. [syngen_xl_notebook.zip](https://github.com/RoyiRa/Linguistic-Binding-in-Diffusion-Models/files/14948196/syngen_xl_notebook.zip)

Did you solve the problem with the application on sdxl?

**Comment by lioo717** [comment]
@jiashenggu @RoyiRa Did you solve the problem with the application on sdxl?
