### ISSUE TITLE
The normalization of attention maps

### ISSUE THREAD

**Issue by tuning12** [RoyiRa/Syntax-Guided-Generation#6]
Hi, thank you for your great work.
The attention maps are normalized before computing the kl divergence of a pair of attention maps, which is mentioned in your paper. However, I haven't found the implementation of the normalization in the code.

**Comment by RoyiRa** [comment]
Thank you for asking. The normalization occurs in the [Categorical](https://pytorch.org/docs/stable/distributions.html) function, see `_symmetric_kl` in `compute_loss.py`.
