### ISSUE TITLE
How to prevent the KL_div from being NaN

### ISSUE THREAD

**Issue by tuning12** [RoyiRa/Syntax-Guided-Generation#7]
Hi. Could you please tell me the precision of your pipeline and why the KL_div won't be NaN? As far as I know, the KL_div is inf when distribution q has a zero value.

**Comment by RoyiRa** [comment]
What model are you running?
If you stick to float32 I never (iirc) had issues with NaN values.

**Comment by tuning12** [comment]
First Thank you for your reply. My question has been solved already.
