### ISSUE TITLE
Is it possible to apply SynGen to SDXL?

### ISSUE THREAD

**Issue by lioo717** [RoyiRa/Syntax-Guided-Generation#8]
@RoyiRa  Sorry for bother you again with the same problem. Have you solve the problem of applying SynGen to SDXL?

**Comment by RoyiRa** [comment]
It works with float32, but not as well as in SD-1.4. My guess is that a hyperparameter search over the layers (how many layers and from which; up, down, mid), scale factor, and number of iterations to update will bridge that gap though.

**Comment by naLWN** [comment]
> 很抱歉再次用同样的问题打扰您。您是否解决了将 SynGen 应用于 SDXL 的问题？
![3aca2478a49ef395f5a7880346be7b0](https://github.com/user-attachments/assets/e943db06-1ffd-4224-94f1-34d875a67b9b)
你好，你跑代码过程中出现过这个问题吗？你是怎么解决的呀？
